apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  # clusterIP: None
  type: NodePort
  ports:
    - port: 9042
      nodePort: 30000
  selector:
    app: cassandra