apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-home-2
  labels:
    type: local
spec:
  storageClassName: fast
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/temp/kube-volume-2"
